elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
  environment:
    - ES_HEAP_SIZE=9g
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
